# Generated by Django 3.1.1 on 2020-10-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('user', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='comment_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('forB', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
